// web/app/components/ViewSelector.vue
<script setup lang="ts">

</script>

<template>
  <div class="join w-full bg-base-200 rounded-full">
    <input
        class="join-item btn rounded-full w-1/2 h-8"
        type="radio"
        name="views"
        aria-label="Daily"
        checked
    />
    <input
        class="join-item btn rounded-full w-1/2 h-8"
        type="radio"
        name="views"
        aria-label="Overview"
    />
  </div>
</template>

<style scoped>

</style>

// web/src/lib/ui/home/ViewSelector.svelte
<script lang="ts">
    import {page} from "$app/state";
</script>

<section class="join w-full md:w-2/5 bg-base-200 rounded-full">
    <a
            href="/daily"
            class="text-base font-medium join-item btn md:btn-sm rounded-full w-1/2 {page.url.pathname === '/daily' ? 'bg-primary' : ''}"
    >
        Daily
    </a>
    <a
            href="/overview"
            class="text-base font-medium join-item btn md:btn-sm rounded-full w-1/2 {page.url.pathname === '/overview' ? 'bg-primary' : ''}"
    >
        Overview
    </a>
</section>
