// web/src/lib/ui/ViewSelector.svelte
<script lang="ts">
    import {page} from "$app/state";
</script>

<section class="join w-full bg-base-200 rounded-full">
    <a
            href="/daily"
            class="join-item btn rounded-full w-1/2 h-8 {page.url.pathname === '/daily' ? 'bg-primary' : ''}"
    >
        Daily
    </a>
    <a
            href="/overview"
            class="join-item btn rounded-full w-1/2 h-8 {page.url.pathname === '/overview' ? 'bg-primary' : ''}"
    >
        Overview
    </a>
</section>

// web/app/components/home/ViewSelector.vue
<script setup lang="ts">
const updateView = async (view: "daily" | "overview") => {
  await navigateTo({
    path: "/",
    query: {
      view: view
    }
  });
};
</script>

<template>
  <div class="join w-full bg-base-200 rounded-full">
    <input
        class="join-item btn rounded-full w-1/2 h-8"
        type="radio"
        name="views"
        aria-label="Daily"
        :checked="$route.query.view === 'daily'"
        @change="updateView('daily')"
    />
    <input
        class="join-item btn rounded-full w-1/2 h-8"
        type="radio"
        name="views"
        aria-label="Overview"
        :checked="$route.query.view === 'overview'"
        @change="updateView('overview')"
    />
  </div>
</template>

<style scoped>

</style>
